/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class TAtrib extends Token
{
    public TAtrib()
    {
        super.setText("<-");
    }

    public TAtrib(int line, int pos)
    {
        super.setText("<-");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TAtrib(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTAtrib(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TAtrib text.");
    }
}
