/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class TCaracter extends Token
{
    public TCaracter()
    {
        super.setText("caracter");
    }

    public TCaracter(int line, int pos)
    {
        super.setText("caracter");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TCaracter(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTCaracter(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TCaracter text.");
    }
}
