/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class TFimRepita extends Token
{
    public TFimRepita()
    {
        super.setText("fim repita");
    }

    public TFimRepita(int line, int pos)
    {
        super.setText("fim repita");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TFimRepita(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTFimRepita(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TFimRepita text.");
    }
}
