/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class TVerdade extends Token
{
    public TVerdade()
    {
        super.setText("verdade");
    }

    public TVerdade(int line, int pos)
    {
        super.setText("verdade");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TVerdade(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTVerdade(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TVerdade text.");
    }
}
