/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class TVetor extends Token
{
    public TVetor()
    {
        super.setText("vetor");
    }

    public TVetor(int line, int pos)
    {
        super.setText("vetor");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TVetor(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTVetor(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TVetor text.");
    }
}
