/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class TXou extends Token
{
    public TXou()
    {
        super.setText("xou");
    }

    public TXou(int line, int pos)
    {
        super.setText("xou");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TXou(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTXou(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TXou text.");
    }
}
