/* This file was generated by SableCC (http://www.sablecc.org/). */

package analysis;

import node.*;

public interface Analysis extends Switch
{
    Object getIn(Node node);
    void setIn(Node node, Object o);
    Object getOut(Node node);
    void setOut(Node node, Object o);

    void caseTPrograma(TPrograma node);
    void caseTInicio(TInicio node);
    void caseTFim(TFim node);
    void caseTFaca(TFaca node);
    void caseTAte(TAte node);
    void caseTSe(TSe node);
    void caseTEntao(TEntao node);
    void caseTSenao(TSenao node);
    void caseTAvalie(TAvalie node);
    void caseTCaso(TCaso node);
    void caseTEnquanto(TEnquanto node);
    void caseTRepita(TRepita node);
    void caseTPara(TPara node);
    void caseTDe(TDe node);
    void caseTPasso(TPasso node);
    void caseTLeia(TLeia node);
    void caseTEscreva(TEscreva node);
    void caseTVar(TVar node);
    void caseTFimSe(TFimSe node);
    void caseTFimEnquanto(TFimEnquanto node);
    void caseTFimPara(TFimPara node);
    void caseTFimRepita(TFimRepita node);
    void caseTCaracter(TCaracter node);
    void caseTInteiro(TInteiro node);
    void caseTLogico(TLogico node);
    void caseTFalso(TFalso node);
    void caseTVerdade(TVerdade node);
    void caseTInterrompa(TInterrompa node);
    void caseTNao(TNao node);
    void caseTOu(TOu node);
    void caseTProcedimento(TProcedimento node);
    void caseTXou(TXou node);
    void caseTE(TE node);
    void caseTVetor(TVetor node);
    void caseTConst(TConst node);
    void caseTMais(TMais node);
    void caseTMenos(TMenos node);
    void caseTMult(TMult node);
    void caseTDivisao(TDivisao node);
    void caseTExponenciacao(TExponenciacao node);
    void caseTResto(TResto node);
    void caseTAtrib(TAtrib node);
    void caseTMaiorq(TMaiorq node);
    void caseTMenorq(TMenorq node);
    void caseTMaiorIgual(TMaiorIgual node);
    void caseTMenorIgual(TMenorIgual node);
    void caseTIgual(TIgual node);
    void caseTDiferente(TDiferente node);
    void caseTVirgula(TVirgula node);
    void caseTDoisPontos(TDoisPontos node);
    void caseTPontoVirgula(TPontoVirgula node);
    void caseTPonto(TPonto node);
    void caseTParenteseDir(TParenteseDir node);
    void caseTParenteseEsq(TParenteseEsq node);
    void caseTNumero(TNumero node);
    void caseTComentario(TComentario node);
    void caseTBlanks(TBlanks node);
    void caseTIdentificador(TIdentificador node);
    void caseTComment(TComment node);
    void caseTCommentEnd(TCommentEnd node);
    void caseTCommentBody(TCommentBody node);
    void caseTStar(TStar node);
    void caseTSlash(TSlash node);
    void caseEOF(EOF node);
    void caseInvalidToken(InvalidToken node);
}
